name: tf
channels:
  - defaults
dependencies:
  - pip=22.3.1
  - numpy=1.23.5
  - pip:
    - easyocr==1.6.2
    - nltk==3.8.1
    - numpy==1.23.5
    - Pillow==9.5.0
    - requests==2.28.1
    - streamlit==1.14.1
    - torch==2.0.0
    - transformers==4.28.1
